namePrefix: ipam-

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-metal3"

bases:
#- crd
#- webhook
- default


patchesJson6902:
- target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: ipaddresses.ipam.metal3.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: ipclaims.ipam.metal3.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: ippools.ipam.metal3.io
  path: patch_crd_webhook_namespace.yaml
