name: build-images-action

permissions:
  contents: read

on:
  push:
    branches:
    - "main"
    - "release-*"
    tags:
    - "v*"

jobs:
  set_ref:
    runs-on: ubuntu-latest
    outputs:
      github_ref: ${{ steps.set_ref.outputs.github_ref }}
    steps:
    - name: Set ref
      id: set_ref
      run: |
        if [[ "${{ github.event_name }}" == "workflow_run" ]] && [[ -n "${{ needs.create-release.outputs.release_tag }}" ]]; then
          echo "GITHUB_REF=refs/heads/${{ needs.create-release.outputs.release_tag }}" >> "${GITHUB_OUTPUT}"
        else
          echo "GITHUB_REF=${{ github.ref }}" >> "${GITHUB_OUTPUT}"
        fi

  build_ipam:
    needs: set_ref
    name: Build IPAM container image
    if: github.repository == 'metal3-io/ip-address-manager'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: "ip-address-manager"
      pushImage: true
      ref: ${{ needs.set_ref.outputs.github_ref }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
