name: Kubesec
on:
  push:
    branches: [main]
  schedule:
  - cron: '30 7 * * 1'

permissions: {}

jobs:
  setup:
    runs-on: ubuntu-20.04
    name: setup

    permissions:
      actions: read
      contents: read

    if: github.repository == 'metal3-io/ip-address-manager'
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Collect all yaml
      id: list_yaml
      run: |
        LIST_YAML="$(find * -type f -name '*.yaml')"
        echo "::set-output name=value::$(IFS=$','; echo $LIST_YAML | jq -cnR '[inputs | select(length>0)]'; IFS=$'\n')"
    outputs:
      matrix: ${{ steps.list_yaml.outputs.value }}

  lint:
    needs: [setup]
    name: Kubesec
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        value: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Run kubesec scanner
      uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14 # v0.0.2
      with:
        input: ${{ matrix.value }}
        format: template
        template: template/sarif.tpl
        output: ${{ matrix.value }}.sarif
        exit-code: "0"

    - name: Save result into a variable
      id: save_result
      run: echo "::set-output name=result::$(cat ${{ matrix.value }}.sarif | jq -c '.runs')"

    - name: Upload Kubesec scan results to GitHub Security tab
      if: ${{ steps.save_result.outputs.result != '[]' }}
      uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a # v2.13.4
      with:
        sarif_file: ${{ matrix.value }}.sarif
