# This file is adapted from https://github.com/google/osv-scanner


name: OSV-Scanner Scan

on:
  schedule:
  - cron: "12 12 * * 1"

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  scan-scheduled:
    permissions:
      actions: read
      contents: read # to fetch code (actions/checkout)
      security-events: write # for uploading SARIF files
    if: ${{ github.repository == 'metal3-io/ip-address-manager' && github.event_name == 'schedule' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8b8e1861d7ab37b197ce153bb19f43cacb6dbddf # v1.8.5
