# This file is adapted from https://github.com/google/osv-scanner

name: OSV-Scanner

permissions: {}

on:
  workflow_call:
    inputs:
      scan-args:
        description: "Custom osv-scanner arguments (See https://google.github.io/osv-scanner/usage/ for options, you cannot set --format or --output)"
        type: string
        default: |-
          -r
          --skip-git
          ./
      results-file-name:
        description: "File name of the result SARIF file"
        type: string
        default: results.sarif
      upload-sarif:
        description: "Whether to upload to Security > Code Scanning"
        type: boolean
        required: false
        default: true
      fail-on-vuln:
        description: "Whether to fail the action on vulnerability found"
        type: boolean
        default: true

jobs:
  scan-pr:
    permissions:
      contents: read # to fetch code (actions/checkout)
      security-events: write # for uploading SARIF files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        fetch-depth: 0
        # Do persist credentials, as we need it for the git checkout later
    - name: "Checkout target branch"
      run: git checkout $GITHUB_BASE_REF
    - name: "Calculate go version"
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # tag=v5.0.1
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: "Run scanner on existing code"
      uses: google/osv-scanner/actions/scanner@645d5b0bb9c14741b2147a5305b684e4abc039e0 # v1.7.3
      continue-on-error: true
      with:
        scan-args: |-
          --format=json
          --output=old-results.json
          ${{ inputs.scan-args }}
    - name: "Checkout current branch"
      run: git checkout $GITHUB_SHA
    - name: "Run scanner on new code"
      uses: google/osv-scanner/actions/scanner@645d5b0bb9c14741b2147a5305b684e4abc039e0 # v1.7.3
      with:
        scan-args: |-
          --format=json
          --output=new-results.json
          ${{ inputs.scan-args }}
      continue-on-error: true
    - name: "Run osv-scanner-reporter"
      uses: google/osv-scanner/actions/reporter@645d5b0bb9c14741b2147a5305b684e4abc039e0 # v1.7.3
      with:
        scan-args: |-
          --output=${{ inputs.results-file-name }}
          --old=old-results.json
          --new=new-results.json
          --gh-annotations=true
          --fail-on-vuln=${{ inputs.fail-on-vuln }}
    # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
    # format to the repository Actions tab.
    - name: "Upload artifact"
      if: "!cancelled()"
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: SARIF file
        path: ${{ inputs.results-file-name }}
        retention-days: 5
    - name: "Upload old scan json results"
      if: "!cancelled()"
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: old-json-results
        path: old-results.json
        retention-days: 5
    - name: "Upload new scan json results"
      if: "!cancelled()"
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: new-json-results
        path: new-results.json
        retention-days: 5
    # Upload the results to GitHub's code scanning dashboard.
    - name: "Upload to code-scanning"
      if: ${{ !cancelled() && inputs.upload-sarif == true }}
      uses: github/codeql-action/upload-sarif@f079b8493333aace61c81488f8bd40919487bd9f # v3.25.7
      with:
        sarif_file: ${{ inputs.results-file-name }}
