name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - "v*"

permissions: {}

jobs:
  build:
    name: tag release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: github.repository == 'metal3-io/ip-address-manager'
    steps:
    - name: Export RELEASE_TAG var
      run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0
    - name: Install go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: '1.22'
    - name: Generate release artifacts and notes
      run: |
        make release
    - name: Release
      uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 # v2.0.6
      with:
        draft: true
        files: out/*
        body_path: releasenotes/${{ env.RELEASE_TAG }}.md
